/**
 * Seed data — the single source of truth for both the in-memory demo store
 * and `supabase/seed.sql` (generated by `npm run seed:sql`).
 *
 * RULES (see BUILD_PROMPT §19):
 *  - Public content here is REAL and credited: every item names its source
 *    organisation, links to the source page and carries its licence.
 *  - Photographs are only bundled (public/media) when their licence allows
 *    reuse (public domain, GODL-India, CC BY / CC BY-SA); the credit and
 *    licence travel with the item. Everything else is link-and-credit only.
 *  - "Archive notes" are short summaries written for this portal from the
 *    linked source page. Numbers in them are copied from that source.
 *  - NCPOR's own material is never copied: external link and credit only.
 *  - The only fictional rows are the two staff-only items that demonstrate
 *    internal and embargoed release control; they are `is_sample: true` and
 *    never public.
 */
import type { CalendarEntry, Expedition, Item, Organization, Profile, Station } from "@/lib/types";
import { SEA_ICE, type SeaIceRow } from "./seaice";

/** Deterministic, valid v4-shaped UUIDs for seed rows. */
export const sid = (n: number) => `00000000-0000-4000-a000-${String(n).padStart(12, "0")}`;

export const ORG_ID = sid(1);
export const org: Organization = { id: ORG_ID, name: "NCPOR", slug: "ncpor", logo_url: null };

/** Demo-mode personas (demo store only; not inserted into Supabase). */
export const demoProfiles: Profile[] = [
  { id: sid(11), full_name: "Sample Member", email: "member@demo.local", avatar_url: null, role: "member", org_id: ORG_ID },
  { id: sid(12), full_name: "Sample Curator", email: "curator@demo.local", avatar_url: null, role: "curator", org_id: ORG_ID },
  { id: sid(13), full_name: "Sample Reviewer", email: "reviewer@demo.local", avatar_url: null, role: "reviewer", org_id: ORG_ID },
  { id: sid(14), full_name: "Sample Admin", email: "admin@demo.local", avatar_url: null, role: "admin", org_id: ORG_ID },
];

/**
 * Stations. Coordinates are APPROXIMATE (rounded, from general public
 * references) and must be verified against NCPOR before any official use.
 */
export const stations: Station[] = [
  { id: sid(21), name: "Maitri", region: "antarctica", lat: -70.77, lng: 11.73, description: "Indian Antarctic research station in the Schirmacher Oasis region (coordinates approximate)." },
  { id: sid(22), name: "Bharati", region: "antarctica", lat: -69.41, lng: 76.19, description: "Indian Antarctic research station in the Larsemann Hills region (coordinates approximate)." },
  { id: sid(23), name: "Himadri", region: "arctic", lat: 78.92, lng: 11.93, description: "Indian Arctic research station at Ny-Ålesund, Svalbard (coordinates approximate)." },
  { id: sid(24), name: "Himansh", region: "himalaya", lat: 32.4, lng: 77.6, description: "Indian high-altitude research station in the Himalaya (coordinates approximate)." },
];

export const EXP = { mosaic: sid(31), e46: sid(32), gakkel: sid(33), ross: sid(34), caml: sid(35) };

export const expeditions: Expedition[] = [
  {
    id: EXP.mosaic, org_id: ORG_ID, code: "MOSAiC", region: "arctic",
    title: "MOSAiC: a year drifting with the Arctic sea ice",
    summary: "The Multidisciplinary drifting Observatory for the Study of Arctic Climate, led by the Alfred Wegener Institute (Germany). The research icebreaker Polarstern left Tromsø on 20 September 2019 and spent a year in the central Arctic, most of it frozen into the ice. 442 experts from 20 nations took part. Source: mosaic-expedition.org.",
    start_date: "2019-09-20", end_date: "2020-10-12", status: "completed", cover_url: "/media/mosaic-ice-camp.jpg", station_id: null, is_sample: false,
  },
  {
    id: EXP.e46, org_id: ORG_ID, code: "46-ISEA", region: "antarctica",
    title: "46th Indian Scientific Expedition to Antarctica",
    summary: "Announced by NCPOR. This page collects reports, data, photos and activities as they are released; the announcement document is linked below.",
    start_date: null, end_date: null, status: "planned", cover_url: "art:ship-ice", station_id: null, is_sample: false,
  },
  {
    id: EXP.ross, org_id: ORG_ID, code: "WHOI-ANT-2007", region: "antarctica",
    title: "Penguins and Lava Flows Expedition, Ross Island",
    summary: "A Woods Hole Oceanographic Institution (USA) “Live from the Poles” expedition, 26 November to 23 December 2007: Adélie penguin biology in the Ross Sea and the weathering of old lava flows on Ross Island and Mt. Morning. Source: polardiscovery.whoi.edu.",
    start_date: "2007-11-26", end_date: "2007-12-23", status: "completed", cover_url: "art:antarctic-coast", station_id: null, is_sample: false,
  },
  {
    id: EXP.gakkel, org_id: ORG_ID, code: "WHOI-ARC-2007", region: "arctic",
    title: "Arctic Seafloor Expedition, Gakkel Ridge",
    summary: "A Woods Hole Oceanographic Institution (USA) “Live from the Poles” expedition, 1 July to 10 August 2007, aboard the Swedish icebreaker Oden: a search for hydrothermal vents on the Gakkel Ridge with the robotic vehicles PUMA and Jaguar. Source: polardiscovery.whoi.edu.",
    start_date: "2007-07-01", end_date: "2007-08-10", status: "completed", cover_url: "art:ocean", station_id: null, is_sample: false,
  },
  {
    id: EXP.caml, org_id: ORG_ID, code: "TAN0802", region: "southern_ocean",
    title: "IPY-CAML Ross Sea voyage, RV Tangaroa",
    summary: "New Zealand's International Polar Year Census of Antarctic Marine Life voyage, led by NIWA. RV Tangaroa left Wellington on 26 January 2008 and returned on 21 March 2008 after surveying the Ross Sea. Source: niwa.co.nz.",
    start_date: "2008-01-26", end_date: "2008-03-21", status: "completed", cover_url: "/media/rv-tangaroa.jpg", station_id: null, is_sample: false,
  },
];

const T0 = "2026-09-30T09:00:00.000Z";

type SeedItem = Omit<Item, "org_id" | "created_at" | "updated_at" | "created_by" | "status" | "visibility" | "embargo_until" | "is_sample" | "language" | "external_url"> &
  Partial<Pick<Item, "status" | "visibility" | "embargo_until" | "created_at" | "is_sample" | "language" | "external_url">>;

const base = (i: SeedItem): Item => ({
  status: "published",
  visibility: "public",
  embargo_until: null,
  created_at: T0,
  is_sample: false,
  language: "en",
  external_url: null,
  ...i,
  org_id: ORG_ID,
  created_by: null,
  updated_at: i.created_at ?? T0,
});

export const ITEM = {
  rMosaic: sid(101), rGakkel: sid(102), rRoss: sid(103), rCaml: sid(104), rInternal: sid(105), rEmbargo: sid(106), rMosaicHi: sid(107),
  dArcticSep: sid(111), dAntarcticFeb: sid(112), dNpdc: sid(113), dMet: sid(114), dArcticMar: sid(115), dAntarcticSep: sid(116), dPangaea: sid(117),
  pAtmos: sid(121), pIce: sid(122), pOcean: sid(123), pComic: sid(124),
  ph1: sid(131), ph2: sid(132), ph3: sid(133), ph4: sid(134), ph5: sid(135), ph6: sid(136), ph7: sid(137), ph8: sid(138),
  ph9: sid(139), ph10: sid(140), ph11: sid(161), ph12: sid(162), ph13: sid(163), ph14: sid(164), ph15: sid(165),
  v1: sid(141), v2: sid(142), v3: sid(143), v4: sid(144), v5: sid(145), v6: sid(146), v7: sid(147),
  aPolarDiscovery: sid(151), aMosaicEdu: sid(152), aBas: sid(153), aAnt: sid(154), a46: sid(155), aArctic: sid(156), aNsf: sid(157), aBasMaps: sid(158),
};

const SRC = {
  mosaicNumbers: "https://mosaic-expedition.org/expedition/mosaic-in-numbers/",
  whoiArctic: "https://polardiscovery.whoi.edu/expedition2/index.html",
  whoiAntarctic: "https://polardiscovery.whoi.edu/expedition3/index.html",
  niwa: "https://niwa.co.nz/vessels/ipy-caml-voyage-antarctica",
  nsidc: "https://nsidc.org/data/g02135/versions/4",
};
const NSIDC_AUTHORS = ["F. Fetterer", "K. Knowles", "W. N. Meier", "M. Savoie", "A. K. Windnagel", "T. Stafford"];
const NSIDC_LICENSE = "NSIDC Sea Ice Index, Version 4 — free to use with citation (doi:10.7265/a98x-0f50)";
const LINK_ONLY = "See source site";
const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`;
const commons = (file: string) => `https://commons.wikimedia.org/wiki/File:${encodeURIComponent(file.replace(/ /g, "_"))}`;

/** A bundled photograph: licence, credit and the Wikimedia Commons page it came from. */
const photo = (p: {
  id: string; slug: string; title: string; description: string; alt: string; by: string; license: string; file: string; date: string | null;
  expedition?: string; station?: string; discipline: string[]; tags: string[];
}): Item =>
  base({
    id: p.id, type: "photo", title: p.title, description: `${p.description} Photo: ${p.by}. Licence: ${p.license}, via Wikimedia Commons.`,
    expedition_id: p.expedition ?? null, station_id: p.station ?? null, discipline: p.discipline, tags: p.tags, authors: [p.by], event_date: p.date,
    license: p.license, source_url: commons(p.file), media_url: `/media/${p.slug}.jpg`, alt_text: p.alt,
  });

/** A video hosted on YouTube by its publisher: embedded and credited, never re-hosted. */
const video = (v: { id: string; yt: string; title: string; description: string; by: string; expedition?: string; station?: string; discipline: string[]; tags: string[] }): Item =>
  base({
    id: v.id, type: "video", title: v.title, description: `${v.description} Published on YouTube by ${v.by}; embedded and credited here.`,
    expedition_id: v.expedition ?? null, station_id: v.station ?? null, discipline: v.discipline, tags: v.tags, authors: [v.by], event_date: null,
    license: "Standard YouTube licence (embedded)", source_url: yt(v.yt), external_url: yt(v.yt), media_url: yt(v.yt),
  });

/** A page hosted by another organisation: link and credit only. */
const link = (l: { id: string; type: Item["type"]; title: string; description: string; by: string; url: string; expedition?: string; discipline: string[]; tags: string[]; date?: string }): Item =>
  base({
    id: l.id, type: l.type, title: l.title, description: l.description, expedition_id: l.expedition ?? null, station_id: null,
    discipline: l.discipline, tags: l.tags, authors: [l.by], event_date: l.date ?? null, license: LINK_ONLY, source_url: l.url, external_url: l.url,
  });

export const items: Item[] = [
  // ------------------------------------------------------------ reports (archive notes written from the linked source)
  base({ id: ITEM.rMosaic, type: "report", title: "MOSAiC in numbers — archive note", description: "A short archive note on the MOSAiC Arctic drift expedition, written for this portal from the expedition's own “in numbers” page. Every figure is copied from that page.", expedition_id: EXP.mosaic, station_id: null, discipline: ["Climate", "Oceanography", "Glaciology"], tags: ["sea ice", "Arctic", "polar bear", "Polarstern"], authors: ["DhruvGyani archive desk", "Alfred Wegener Institute (source)"], event_date: "2020-10-12", license: "Archive note; facts credited to mosaic-expedition.org", source_url: SRC.mosaicNumbers, external_url: SRC.mosaicNumbers }),
  base({ id: ITEM.rGakkel, type: "report", title: "Arctic Seafloor Expedition, Gakkel Ridge 2007 — archive note", description: "An archive note on the Woods Hole Oceanographic Institution expedition that searched for hydrothermal vents under the Arctic sea ice, written from the expedition page.", expedition_id: EXP.gakkel, station_id: null, discipline: ["Oceanography", "Geology"], tags: ["Arctic", "seafloor", "hydrothermal vents", "sea ice"], authors: ["DhruvGyani archive desk", "Woods Hole Oceanographic Institution (source)"], event_date: "2007-08-10", license: "Archive note; facts credited to polardiscovery.whoi.edu", source_url: SRC.whoiArctic, external_url: SRC.whoiArctic }),
  base({ id: ITEM.rRoss, type: "report", title: "Penguins and Lava Flows Expedition, Ross Island 2007 — archive note", description: "An archive note on the Woods Hole Oceanographic Institution expedition to Ross Island: Adélie penguins and the weathering of old lava flows, written from the expedition page.", expedition_id: EXP.ross, station_id: null, discipline: ["Biology", "Geology"], tags: ["Antarctica", "penguin", "volcano", "Ross Sea"], authors: ["DhruvGyani archive desk", "Woods Hole Oceanographic Institution (source)"], event_date: "2007-12-23", license: "Archive note; facts credited to polardiscovery.whoi.edu", source_url: SRC.whoiAntarctic, external_url: SRC.whoiAntarctic }),
  base({ id: ITEM.rCaml, type: "report", title: "IPY-CAML Ross Sea voyage, RV Tangaroa 2008 — archive note", description: "An archive note on New Zealand's Census of Antarctic Marine Life voyage to the Ross Sea, written from NIWA's voyage pages.", expedition_id: EXP.caml, station_id: null, discipline: ["Biology", "Oceanography"], tags: ["Southern Ocean", "Ross Sea", "marine life", "Antarctica"], authors: ["DhruvGyani archive desk", "NIWA (source)"], event_date: "2008-03-21", license: "Archive note; facts credited to niwa.co.nz", source_url: SRC.niwa, external_url: SRC.niwa }),
  base({ id: ITEM.rInternal, type: "report", title: "Station Logistics Debrief (Sample, internal)", description: "Fictional internal debrief. Marked internal: never shown publicly and never sent to an AI service.", expedition_id: EXP.e46, station_id: sid(21), discipline: ["Logistics"], tags: ["logistics"], authors: ["Sample Station Team"], event_date: "2026-02-20", license: null, source_url: null, is_sample: true, status: "draft", visibility: "internal" }),
  base({ id: ITEM.rEmbargo, type: "report", title: "Preliminary Snow Chemistry Results (Sample, embargoed)", description: "Fictional embargoed item. Hidden from public pages, search and AI until the release date.", expedition_id: EXP.e46, station_id: sid(21), discipline: ["Chemistry"], tags: ["snow chemistry"], authors: ["Sample Lab Team"], event_date: "2026-03-10", license: null, source_url: null, is_sample: true, status: "published", visibility: "public", embargo_until: "2027-06-01T00:00:00.000Z" }),
  base({ id: ITEM.rMosaicHi, type: "report", title: "मोज़ेक अभियान: आँकड़ों में — अभिलेख टिप्पणी", description: "आर्कटिक के मोज़ेक (MOSAiC) अभियान पर हिंदी में एक संक्षिप्त अभिलेख टिप्पणी। सभी आँकड़े अभियान की आधिकारिक वेबसाइट से लिए गए हैं।", expedition_id: EXP.mosaic, station_id: null, discipline: ["Climate"], tags: ["आर्कटिक", "समुद्री बर्फ", "हिंदी"], authors: ["ध्रुवज्ञानी अभिलेख डेस्क", "Alfred Wegener Institute (स्रोत)"], event_date: "2020-10-12", language: "hi", license: "अभिलेख टिप्पणी; तथ्य mosaic-expedition.org से", source_url: SRC.mosaicNumbers, external_url: SRC.mosaicNumbers }),

  // ------------------------------------------------------------ datasets
  base({ id: ITEM.dArcticSep, type: "dataset", title: "Arctic sea-ice extent, September 1979–2025 (NSIDC Sea Ice Index)", description: "Monthly mean sea-ice extent and area for September, the month of the Arctic minimum, from the satellite record. Real observations from the NSIDC Sea Ice Index, Version 4; values are in million square kilometres.", expedition_id: null, station_id: null, discipline: ["Climate", "Oceanography"], tags: ["sea ice", "Arctic", "time series", "satellite"], authors: NSIDC_AUTHORS, event_date: "2025-09-30", license: NSIDC_LICENSE, source_url: SRC.nsidc, media_url: "/data/arctic-sea-ice-extent-september.csv" }),
  base({ id: ITEM.dAntarcticFeb, type: "dataset", title: "Antarctic sea-ice extent, February 1979–2026 (NSIDC Sea Ice Index)", description: "Monthly mean sea-ice extent and area for February, the month of the Antarctic minimum. Real observations from the NSIDC Sea Ice Index, Version 4; values are in million square kilometres.", expedition_id: null, station_id: null, discipline: ["Climate", "Oceanography"], tags: ["sea ice", "Antarctica", "Southern Ocean", "time series"], authors: NSIDC_AUTHORS, event_date: "2026-02-28", license: NSIDC_LICENSE, source_url: SRC.nsidc, media_url: "/data/antarctic-sea-ice-extent-february.csv" }),
  base({ id: ITEM.dArcticMar, type: "dataset", title: "Arctic sea-ice extent, March 1979–2026 (NSIDC Sea Ice Index)", description: "Monthly mean sea-ice extent and area for March, the month of the Arctic winter maximum. Real observations from the NSIDC Sea Ice Index, Version 4; values are in million square kilometres.", expedition_id: null, station_id: null, discipline: ["Climate", "Oceanography"], tags: ["sea ice", "Arctic", "time series", "satellite"], authors: NSIDC_AUTHORS, event_date: "2026-03-31", license: NSIDC_LICENSE, source_url: SRC.nsidc, media_url: "/data/arctic-sea-ice-extent-march.csv" }),
  base({ id: ITEM.dAntarcticSep, type: "dataset", title: "Antarctic sea-ice extent, September 1979–2025 (NSIDC Sea Ice Index)", description: "Monthly mean sea-ice extent and area for September, the month of the Antarctic winter maximum. Real observations from the NSIDC Sea Ice Index, Version 4; values are in million square kilometres.", expedition_id: null, station_id: null, discipline: ["Climate", "Oceanography"], tags: ["sea ice", "Antarctica", "Southern Ocean", "time series"], authors: NSIDC_AUTHORS, event_date: "2025-09-30", license: NSIDC_LICENSE, source_url: SRC.nsidc, media_url: "/data/antarctic-sea-ice-extent-september.csv" }),
  link({ id: ITEM.dNpdc, type: "dataset", title: "National Polar Data Center (NPDC) — external link", description: "External link to NCPOR's National Polar Data Center. Data is hosted and licensed by NCPOR; DhruvGyani links and credits only.", by: "NCPOR", url: "https://npdc.ncpor.res.in", discipline: ["Data"], tags: ["data portal", "NCPOR"] }),
  link({ id: ITEM.dMet, type: "dataset", title: "Antarctic Meteorological Data Portal — external link", description: "External link to NCPOR's Antarctic meteorological data portal. Data is hosted and licensed by NCPOR; DhruvGyani links and credits only.", by: "NCPOR", url: "https://data.ncpor.res.in", discipline: ["Meteorology", "Data"], tags: ["weather station", "data portal", "NCPOR"] }),
  link({ id: ITEM.dPangaea, type: "dataset", title: "MOSAiC datasets on PANGAEA — external link", description: "External link to the PANGAEA data publisher's search for MOSAiC, where the expedition's datasets are published with their own DOIs and licences.", by: "PANGAEA", url: "https://www.pangaea.de/?q=mosaic", expedition: EXP.mosaic, discipline: ["Data", "Climate"], tags: ["data portal", "Arctic", "sea ice"] }),

  // ------------------------------------------------------------ publications (open-access papers: DOI link and credit)
  link({ id: ITEM.pAtmos, type: "publication", title: "Overview of the MOSAiC expedition: Atmosphere", description: "Peer-reviewed overview paper by the MOSAiC atmosphere team, led by Matthew D. Shupe. Published in Elementa: Science of the Anthropocene, volume 10 (2022). Open access; DhruvGyani links to the DOI.", by: "M. D. Shupe et al.", url: "https://doi.org/10.1525/elementa.2021.00060", expedition: EXP.mosaic, discipline: ["Meteorology", "Climate"], tags: ["Arctic", "atmosphere", "MOSAiC"], date: "2022-01-04" }),
  link({ id: ITEM.pIce, type: "publication", title: "Overview of the MOSAiC expedition: Snow and sea ice", description: "Peer-reviewed overview paper by the MOSAiC snow and sea-ice team, led by Marcel Nicolaus. Published in Elementa: Science of the Anthropocene, volume 10 (2022). Open access; DhruvGyani links to the DOI.", by: "M. Nicolaus et al.", url: "https://doi.org/10.1525/elementa.2021.000046", expedition: EXP.mosaic, discipline: ["Glaciology", "Climate"], tags: ["Arctic", "sea ice", "snow", "MOSAiC"] }),
  link({ id: ITEM.pOcean, type: "publication", title: "Overview of the MOSAiC expedition: Physical oceanography", description: "Peer-reviewed overview paper by the MOSAiC ocean team, led by Benjamin Rabe, describing a full year of physical oceanography observations made during the drift. Published in Elementa: Science of the Anthropocene, volume 10 (2022). Open access; DhruvGyani links to the DOI.", by: "B. Rabe et al.", url: "https://doi.org/10.1525/elementa.2021.00062", expedition: EXP.mosaic, discipline: ["Oceanography"], tags: ["Arctic", "ocean", "MOSAiC"] }),
  link({ id: ITEM.pComic, type: "publication", title: "“Polar Sciences: A Peek into NCPOR” comic book — external link", description: "External link to NCPOR's news post about its comic book. The comic is NCPOR's work; DhruvGyani links and credits only.", by: "NCPOR", url: "https://www.ncpor.res.in/news/view/790", discipline: ["Outreach"], tags: ["comic", "students", "NCPOR"] }),

  // ------------------------------------------------------------ photographs (bundled under their licences, with credit)
  photo({ id: ITEM.ph1, slug: "mosaic-ice-camp", file: "20191011 MOSAiCLeg1 StefanHendricks 028.jpg", title: "Setting up the MOSAiC ice camp beside Polarstern", description: "The ice camp being set up in front of RV Polarstern during leg 1 of the MOSAiC expedition, autumn 2019.", alt: "An icebreaker moored against an ice floe at sunset, with people and equipment spread out on the ice.", by: "Stefan Hendricks / Alfred Wegener Institute", license: "CC BY-SA 4.0", date: "2019-10-11", expedition: EXP.mosaic, discipline: ["Glaciology"], tags: ["sea ice", "Arctic", "Polarstern", "fieldwork"] }),
  photo({ id: ITEM.ph2, slug: "polarstern-polar-night", file: "Polarstern shrouded in darkness ESA21521072.jpeg", title: "Polarstern in the polar night", description: "RV Polarstern lit up in the darkness of the Arctic winter during the MOSAiC drift.", alt: "A ship's lights glowing through blowing snow in the dark, seen across rough sea ice.", by: "Esther Horvath / Alfred Wegener Institute", license: "CC BY-SA 3.0 IGO", date: null, expedition: EXP.mosaic, discipline: ["Outreach"], tags: ["polar night", "Arctic", "Polarstern", "night sky"] }),
  photo({ id: ITEM.ph3, slug: "mosaic-polar-bears", file: "Polar bears chewing cables.jpg", title: "Polar bears inspect instrument cables at MOSAiC", description: "Polar bears chewing on power cables for field instruments during the MOSAiC expedition, October 2019.", alt: "Two polar bears on sea ice at night, chewing orange cables beside instrument stands.", by: "Janek Uin", license: "CC BY 4.0", date: "2019-10-10", expedition: EXP.mosaic, discipline: ["Biology"], tags: ["polar bear", "Arctic", "sea ice", "wildlife"] }),
  photo({ id: ITEM.ph4, slug: "mosaic-scientist-polarstern", file: "Scientist in front of rv polarstern.jpg", title: "Carrying equipment across the ice at MOSAiC", description: "A scientist carries equipment over the ice in front of RV Polarstern at the start of the MOSAiC expedition.", alt: "A person in a red suit pulling a sledge across the ice beside the icebreaker Polarstern at dusk.", by: "Janek Uin", license: "CC BY 4.0", date: "2019-10-05", expedition: EXP.mosaic, discipline: ["Outreach"], tags: ["fieldwork", "Arctic", "Polarstern"] }),
  photo({ id: ITEM.ph5, slug: "mosaic-meltwater", file: "Meltwater MOSAiC.jpg", title: "Summer melt ponds on the MOSAiC floe", description: "Surface melt ponds on the ice during the MOSAiC expedition in July 2020, with Polarstern in the distance.", alt: "Blue-green melt ponds on sea ice with sledges and equipment in the foreground and a ship in the haze beyond.", by: "Evgenii Salganik", license: "CC BY-SA 4.0", date: "2020-07-21", expedition: EXP.mosaic, discipline: ["Glaciology", "Climate"], tags: ["sea ice", "melt pond", "Arctic", "cryosphere"] }),
  photo({ id: ITEM.ph6, slug: "maitri-station-2017", file: "मैत्री, भारतीय स्टेशन अंटार्कटिक महाद्वीप.jpg", title: "Maitri station, Antarctica", description: "Maitri, India's research station in the Schirmacher Oasis, photographed in January 2017.", alt: "Snow-covered ground with a long station building on the horizon and a raised walkway on stilts.", by: "Prakash Khatarkar", license: "CC BY-SA 4.0", date: "2017-01-15", station: sid(21), discipline: ["Outreach"], tags: ["Maitri", "Antarctica", "station life"] }),
  photo({ id: ITEM.ph7, slug: "maitri-aerial-2005", file: "An aerial view of the Indian Station Maitri, Antarctica on February 2, 2005.jpg", title: "Maitri station from the air, 2005", description: "An aerial view of the Indian station Maitri, Antarctica, on 2 February 2005, released by the Press Information Bureau.", alt: "Aerial view of long white station buildings and orange containers on brown rocky ground beside small lakes.", by: "Ministry of Science and Technology, Government of India", license: "GODL-India", date: "2005-02-02", station: sid(21), discipline: ["Outreach"], tags: ["Maitri", "Antarctica", "aerial"] }),
  photo({ id: ITEM.ph8, slug: "second-indian-expedition-1982", file: "Visit to the Russian station Novolazarevskaya during the Second Indian Antarctic Expedition.jpg", title: "Second Indian Antarctic Expedition, December 1982", description: "Members of the Second Indian Antarctic Expedition visiting the Russian station Novolazarevskaya in the Schirmacher Hills, December 1982.", alt: "Expedition members in red suits standing on rocky ground beside a long station building on stilts.", by: "Pavan Nair", license: "CC BY-SA 4.0", date: "1982-12-25", station: sid(21), discipline: ["History"], tags: ["Antarctica", "history", "Indian expedition"] }),
  photo({ id: ITEM.ph9, slug: "ny-alesund-station", file: "Ny-Ålesund 2013 06 07 3651 (10178976586).jpg", title: "Sverdrup station, Ny-Ålesund — the research village that hosts Himadri", description: "The Sverdrup research station at Ny-Ålesund, Svalbard, on Kongsfjorden. India's Himadri station is in the same research village.", alt: "A wooden sign reading Sverdrup Stasjonen on the wall of a grey and orange station building.", by: "Harvey Barrison", license: "CC BY-SA 2.0", date: "2013-06-07", station: sid(23), discipline: ["Outreach"], tags: ["Arctic", "fjord", "Svalbard", "Himadri"] }),
  photo({ id: ITEM.ph10, slug: "emperor-penguins-weddell", file: "Weddellsea-ant-iv3-13 hg.jpg", title: "Emperor penguin colony, Weddell Sea", description: "A colony of emperor penguins photographed during the Polarstern expedition ANT-IV/3 in 1985.", alt: "A large colony of emperor penguins standing on sea ice under a blue sky.", by: "Hannes Grobe", license: "CC BY-SA 4.0", date: null, discipline: ["Biology"], tags: ["penguin", "Antarctica", "sea ice", "wildlife"] }),
  photo({ id: ITEM.ph11, slug: "south-pole-aurora", file: "Amundsen-Scott marsstation ray h edit.jpg", title: "Aurora over Amundsen-Scott South Pole Station", description: "A 25-second exposure under a full moon during the Antarctic night at the South Pole, July 2005.", alt: "A green aurora band across a starry sky above station buildings lit red and yellow.", by: "Chris Danals / National Science Foundation", license: "Public domain (NSF)", date: null, discipline: ["Outreach"], tags: ["aurora", "Antarctica", "night sky", "station life"] }),
  photo({ id: ITEM.ph12, slug: "mcmurdo-station", file: "McMurdo Station in Antarctica.jpg", title: "McMurdo Station, Ross Island", description: "McMurdo Station, the main U.S. coastal station in Antarctica, at the southern tip of Ross Island, seen from the Arrival Heights web camera.", alt: "Station buildings spread out below a dark conical hill, with sea ice beyond.", by: "U.S. Antarctic Program / National Science Foundation", license: "Public domain (USAP)", date: "2014-01-06", discipline: ["Outreach"], tags: ["Antarctica", "Ross Sea", "station life"] }),
  photo({ id: ITEM.ph13, slug: "ice-core-drill", file: "Ice-core drill hg.jpg", title: "Preparing an ice-core drill, Kohnen Station", description: "The ice corer being prepared for deployment for the EPICA project at Kohnen Station, Dronning Maud Land, Antarctica.", alt: "Two people silhouetted in a trench cut into the ice, beside a long ice-core drill.", by: "Hannes Grobe / Alfred Wegener Institute", license: "CC BY-SA 2.5", date: "2002-02-10", discipline: ["Glaciology"], tags: ["ice core", "Antarctica", "fieldwork", "cryosphere"] }),
  photo({ id: ITEM.ph14, slug: "rv-tangaroa", file: "RV Tangaroa.jpg", title: "RV Tangaroa", description: "New Zealand's research vessel Tangaroa, the ship of the 2008 IPY-CAML voyage to the Ross Sea.", alt: "A blue and white research ship with the name Tangaroa on its bow, under way at sea.", by: "Dave Allen / NIWA", license: "CC BY 3.0", date: "2010-12-12", expedition: EXP.caml, discipline: ["Oceanography"], tags: ["ship", "Southern Ocean", "Ross Sea"] }),
  photo({ id: ITEM.ph15, slug: "arctic-melt-ponds", file: "Arctic sea ice melt (956).jpg", title: "Sampling melt ponds on Arctic sea ice", description: "Scientists scoop water from melt ponds on sea ice in the Chukchi Sea during NASA's ICESCAPE mission, 10 July 2011.", alt: "Two researchers in red suits kneeling at the edge of a turquoise melt pond, with a red and white icebreaker behind them.", by: "Kathryn Hansen / NASA", license: "Public domain (NASA)", date: "2011-07-10", discipline: ["Oceanography", "Climate"], tags: ["sea ice", "melt pond", "Arctic", "fieldwork"] }),

  // ------------------------------------------------------------ videos (embedded from the publisher's YouTube channel)
  video({ id: ITEM.v1, yt: "HoppMFMZ5Y8", title: "Into the Polar Night: MOSAiC planetarium show", description: "A planetarium show about the MOSAiC expedition's year in the Arctic ice.", by: "CIRES, University of Colorado Boulder", expedition: EXP.mosaic, discipline: ["Outreach", "Climate"], tags: ["Arctic", "polar night", "sea ice", "students"] }),
  video({ id: ITEM.v2, yt: "oLk3LfeMXv0", title: "MOSAiC — Welcome Back, Polarstern!", description: "The Alfred Wegener Institute's video marking Polarstern's return from the MOSAiC drift.", by: "Alfred Wegener Institute", expedition: EXP.mosaic, discipline: ["Outreach"], tags: ["Arctic", "Polarstern", "MOSAiC"] }),
  video({ id: ITEM.v3, yt: "7BYhAmCycw0", title: "Learn MOSAiC: A Participant's View of MOSAiC, by John Cassano", description: "A lecture from the MOSAiC course giving a participant's view of the expedition.", by: "CIRES, University of Colorado Boulder", expedition: EXP.mosaic, discipline: ["Education", "Meteorology"], tags: ["Arctic", "students", "explainer", "MOSAiC"] }),
  video({ id: ITEM.v4, yt: "EnAdOBfCcRc", title: "MOSAiC Is Ready To Launch!", description: "A film released as the MOSAiC expedition prepared to launch.", by: "CIRES, University of Colorado Boulder", expedition: EXP.mosaic, discipline: ["Outreach"], tags: ["Arctic", "MOSAiC", "explainer"] }),
  video({ id: ITEM.v5, yt: "kZ_4h9UA7Uo", title: "Expedition Antarctica — documentary", description: "A documentary following marine scientists aboard RV Tangaroa on the 2008 census of Antarctic marine life in the Ross Sea.", by: "Free Documentary", expedition: EXP.caml, discipline: ["Biology", "Oceanography"], tags: ["Antarctica", "Southern Ocean", "marine life", "ship"] }),
  video({ id: ITEM.v6, yt: "BMUn8U4tLfU", title: "Himadri, India's first Arctic research station", description: "A short film from the Ministry of Earth Sciences about India's Himadri station at Ny-Ålesund.", by: "Ministry of Earth Sciences, Government of India", station: sid(23), discipline: ["Outreach"], tags: ["Arctic", "Himadri", "station life", "NCPOR"] }),
  video({ id: ITEM.v7, yt: "3h9Ltuxsxug", title: "Himadri at Ny-Ålesund marks India's Arctic presence", description: "A Ministry of Earth Sciences clip on Himadri and climate research by NCPOR in the Arctic.", by: "Ministry of Earth Sciences, Government of India", station: sid(23), discipline: ["Outreach", "Climate"], tags: ["Arctic", "Himadri", "NCPOR"] }),

  // ------------------------------------------------------------ institutional activities and outreach programmes
  link({ id: ITEM.aPolarDiscovery, type: "activity", title: "Polar Discovery: Live from the Poles (WHOI outreach programme)", description: "Woods Hole Oceanographic Institution's outreach programme that followed five polar expeditions between 2007 and 2009 with daily dispatches, photo essays, video and live satellite-phone calls to museum audiences. Hosted by WHOI; linked and credited only.", by: "Woods Hole Oceanographic Institution", url: "https://polardiscovery.whoi.edu/", discipline: ["Outreach", "Education"], tags: ["outreach", "students", "schools", "Arctic", "Antarctica"] }),
  link({ id: ITEM.aMosaicEdu, type: "activity", title: "MOSAiC education and outreach resources (CIRES)", description: "The University of Colorado Boulder's MOSAiC education site: classroom activities, 360-degree videos and a free online course with lectures by MOSAiC scientists. Hosted by CIRES; linked and credited only.", by: "CIRES, University of Colorado Boulder", url: "https://mosaic.colorado.edu/", expedition: EXP.mosaic, discipline: ["Outreach", "Education"], tags: ["teachers", "students", "schools", "cryosphere", "Arctic"] }),
  link({ id: ITEM.aBas, type: "activity", title: "British Antarctic Survey image and video library — external link", description: "The British Antarctic Survey's library of polar photography and video, including a historic collection reaching back to the 1940s. Images are BAS copyright; DhruvGyani links and credits only.", by: "British Antarctic Survey", url: "https://www.bas.ac.uk/data/our-data/images/", discipline: ["Outreach"], tags: ["Antarctica", "photo library", "outreach"] }),
  link({ id: ITEM.aBasMaps, type: "activity", title: "British Antarctic Survey map catalogue — external link", description: "Maps of the polar regions produced by the British Antarctic Survey's Mapping and Geographic Information Centre. Hosted by BAS; linked and credited only.", by: "British Antarctic Survey", url: "https://www.bas.ac.uk/data/our-data/maps/", discipline: ["Outreach", "Data"], tags: ["Antarctica", "maps", "outreach"] }),
  link({ id: ITEM.aNsf, type: "activity", title: "NSF polar image collection — external link", description: "A set of polar images published by the U.S. National Science Foundation. Hosted by NSF; linked and credited only.", by: "U.S. National Science Foundation", url: "https://www.nsf.gov/virtual-backgrounds/polar", discipline: ["Outreach"], tags: ["Antarctica", "Arctic", "photo library", "outreach"] }),
  link({ id: ITEM.aAnt, type: "activity", title: "NCPOR Antarctic programme — external link", description: "External link to NCPOR's page about its Antarctic programme. Content is hosted by NCPOR; DhruvGyani links and credits only.", by: "NCPOR", url: "https://ncpor.res.in/antarcticas", discipline: ["Programme"], tags: ["Antarctica", "NCPOR", "Maitri"] }),
  link({ id: ITEM.aArctic, type: "activity", title: "NCPOR Arctic programme — external link", description: "External link to NCPOR's page about its Arctic programme. Content is hosted by NCPOR; DhruvGyani links and credits only.", by: "NCPOR", url: "https://ncpor.res.in/arctics", discipline: ["Programme"], tags: ["Arctic", "NCPOR", "Himadri"] }),
  link({ id: ITEM.a46, type: "activity", title: "46-ISEA webpage advertisement (PDF) — external link", description: "External link to NCPOR's advertisement document for the 46th Indian Scientific Expedition to Antarctica. Hosted by NCPOR; linked and credited only.", by: "NCPOR", url: "http://isea.ncpor.res.in/forms/46-ISEA%20Webpage%20Advertisment.pdf", expedition: EXP.e46, discipline: ["Programme"], tags: ["46-ISEA", "announcement", "Antarctica"] }),
];

const NOTE = "Archive note written for DhruvGyani from the linked source page.";

/**
 * Item text, page by page: the passages that search, explainers, quizzes and
 * the Content Studio cite. Archive notes restate facts from the source named
 * on the item; link-only items get a one-line pointer.
 */
export const archiveNotes: Record<string, string[]> = {
  [ITEM.rMosaic]: [
    `MOSAiC, the Multidisciplinary drifting Observatory for the Study of Arctic Climate, was led by the Alfred Wegener Institute. The research icebreaker Polarstern sailed from Tromsø on 20 September 2019 and the expedition lasted 389 days. 442 experts from 20 nations travelled to the Arctic in phases during the year. ${NOTE}`,
    "Polarstern spent 10 months frozen into the sea ice and drifted 3400 km with it. The team worked for 300 days on the first MOSAiC ice floe and 30 days on a second floe. The drift took the ship to within 156 kilometres of the North Pole. The lowest temperature measured was -42.3 °C, on 10 March 2020.",
    "The team sighted 60 polar bears during the year. 7 icebreakers and research ships supported the expedition, and 247 monitoring stations were set up on the ice, up to 50 km from the ship. The deepest ocean measurement reached 4,297 m and the highest atmospheric measurement reached 36,278 m.",
  ],
  [ITEM.rGakkel]: [
    `The Arctic Seafloor Expedition ran from 1 July to 10 August 2007, a 40-day cruise aboard the Swedish icebreaker Oden. It went to the Gakkel Ridge in the eastern Arctic Ocean, the northern extension of the Mid-Atlantic Ridge. ${NOTE}`,
    "The team set out to see whether active hydrothermal vents exist on the ridge, to find them, and to learn whether the communities of life around them differ from those elsewhere. They used 2 robotic autonomous underwater vehicles, PUMA and Jaguar, built to be lowered through holes in the sea ice and explore the deep Arctic Ocean.",
  ],
  [ITEM.rRoss]: [
    `The Penguins and Lava Flows Expedition ran from 26 November to 23 December 2007 on Ross Island and at Mt. Morning in Antarctica. Penguin biologists David Ainley and Grant Ballard worked alongside geologists Mark Kurz and Adam Soule and graduate student Andrea Burke. ${NOTE}`,
    "The biologists continued a 55-year-long study of Adélie penguins. About 4,000 Adélie penguin pairs and their chicks live at Cape Royds, about 15 miles north of McMurdo Station, and about 100,000 pairs live at Cape Crozier. The geologists studied how lava flows that erupted between 25,000 and 300,000 years ago have weathered, to learn about past climate and the history of the ice sheet.",
  ],
  [ITEM.rCaml]: [
    `New Zealand's International Polar Year Census of Antarctic Marine Life voyage was led by NIWA aboard RV Tangaroa. Voyage TAN0802 left Wellington on 26 January 2008 and returned to Wellington on 21 March 2008. ${NOTE}`,
    "A team of 26 scientists and 18 crew surveyed the Ross Sea and the waters around Scott Island and the Balleny Islands. They collected more than 30,000 specimens using bottom trawls, beam trawls, epibenthic sleds, grabs and plankton nets, in the worst ice conditions documented in the Ross Sea in 30 years.",
  ],
  [ITEM.rInternal]: ["SAMPLE - internal. Station logistics debrief: fuel handling, generator maintenance schedule and cargo notes. This item is internal and must never be sent to an AI service."],
  [ITEM.rEmbargo]: ["SAMPLE - embargoed. Preliminary snow chemistry results pending peer review. This item is embargoed and must not appear publicly or be sent to an AI service before its release date."],
  [ITEM.rMosaicHi]: [
    "मोज़ेक (MOSAiC) आर्कटिक का एक वर्ष लंबा अभियान था, जिसका नेतृत्व जर्मनी के अल्फ्रेड वेगेनर संस्थान ने किया। अनुसंधान पोत पोलरस्टर्न 20 सितंबर 2019 को ट्रोम्सो से रवाना हुआ और अभियान 389 दिन चला। 20 देशों के 442 विशेषज्ञ इसमें शामिल हुए। यह अभिलेख टिप्पणी अभियान की आधिकारिक वेबसाइट के आधार पर ध्रुवज्ञानी के लिए लिखी गई है।",
    "पोत 10 महीने समुद्री बर्फ में जमा रहा और बर्फ के साथ 3400 km बहा। सबसे कम तापमान -42.3 °C दर्ज हुआ। टीम ने वर्ष भर में 60 ध्रुवीय भालू देखे।",
  ],
  [ITEM.dArcticSep]: ["Arctic sea-ice extent and area for each September from 1979 to 2025, in million square kilometres, from the NSIDC Sea Ice Index, Version 4. September is the month of the Arctic minimum."],
  [ITEM.dAntarcticFeb]: ["Antarctic sea-ice extent and area for each February from 1979 to 2026, in million square kilometres, from the NSIDC Sea Ice Index, Version 4. February is the month of the Antarctic minimum."],
  [ITEM.dArcticMar]: ["Arctic sea-ice extent and area for each March from 1979 to 2026, in million square kilometres, from the NSIDC Sea Ice Index, Version 4. March is the month of the Arctic winter maximum."],
  [ITEM.dAntarcticSep]: ["Antarctic sea-ice extent and area for each September from 1979 to 2025, in million square kilometres, from the NSIDC Sea Ice Index, Version 4. September is the month of the Antarctic winter maximum."],
  [ITEM.dNpdc]: ["External link: National Polar Data Center, hosted by NCPOR. Visit the source site for datasets, metadata and licensing."],
  [ITEM.dMet]: ["External link: Antarctic meteorological data portal, hosted by NCPOR. Visit the source site for data and terms of use."],
  [ITEM.dPangaea]: ["External link: MOSAiC datasets published by PANGAEA. Visit the source site for the data, DOIs and licences."],
  [ITEM.pAtmos]: ["Overview of the MOSAiC expedition: Atmosphere. Shupe and co-authors, Elementa: Science of the Anthropocene, volume 10, 2022. Open-access overview paper from the MOSAiC atmosphere team; read it at the DOI link."],
  [ITEM.pIce]: ["Overview of the MOSAiC expedition: Snow and sea ice. Nicolaus and co-authors, Elementa: Science of the Anthropocene, volume 10, 2022. Open-access overview paper from the MOSAiC snow and sea-ice team; read it at the DOI link."],
  [ITEM.pOcean]: ["Overview of the MOSAiC expedition: Physical oceanography. Rabe and co-authors, Elementa: Science of the Anthropocene, volume 10, 2022. Open-access overview paper describing a full year of ocean observations during the drift; read it at the DOI link."],
  [ITEM.pComic]: ["External link: NCPOR news post about the comic book Polar Sciences: A Peek into NCPOR. Visit the source site to read it."],
  [ITEM.aPolarDiscovery]: [
    "Polar Discovery: Live from the Poles is an outreach programme of the Woods Hole Oceanographic Institution, funded by the U.S. National Science Foundation. It followed 5 expeditions: the North Pole Observatory in April 2007, the Arctic Seafloor expedition in July and August 2007, Penguins and Lava Flows in Antarctica in November and December 2007, Greenland's Glaciers in July and August 2008, and the Bering Sea Ecosystem in April and May 2009. A photographer and a science writer sent daily dispatches and photo essays, and scientists spoke to museum audiences by satellite phone.",
  ],
  [ITEM.aMosaicEdu]: ["External link: MOSAiC education and outreach resources from CIRES at the University of Colorado Boulder, including classroom activities, 360-degree videos and a free online course taught by MOSAiC scientists."],
  [ITEM.aBas]: ["External link: the British Antarctic Survey image and video library. Images are BAS copyright; visit the source site for terms of use."],
  [ITEM.aBasMaps]: ["External link: the British Antarctic Survey map catalogue, produced by its Mapping and Geographic Information Centre."],
  [ITEM.aNsf]: ["External link: polar images published by the U.S. National Science Foundation."],
  [ITEM.aAnt]: ["External link: NCPOR page about the Indian Antarctic programme. Visit the source site for details."],
  [ITEM.aArctic]: ["External link: NCPOR page about the Indian Arctic programme. Visit the source site for details."],
  [ITEM.a46]: ["External link: NCPOR advertisement document for the 46th Indian Scientific Expedition to Antarctica. Visit the source site for details."],
};
// photographs and videos are searchable through their caption and credit
for (const i of items) {
  if ((i.type === "photo" || i.type === "video") && !archiveNotes[i.id]) archiveNotes[i.id] = [`${i.title}. ${i.description}`];
}

/** Deterministic chunk IDs: item order × page. */
export function chunkId(itemId: string, page: number) {
  const n = Number(itemId.slice(-4));
  return sid(10000 + n * 10 + page);
}

// ------------------------------------------------------------ datasets: real NSIDC Sea Ice Index series
const seaIceCsv = (rows: SeaIceRow[]) => () => ["year,extent_million_km2,area_million_km2", ...rows.map(([y, e, a]) => `${y},${e ?? ""},${a ?? ""}`)].join("\n") + "\n";
const SEA_ICE_UNITS = { extent_million_km2: "million km²", area_million_km2: "million km²" };

export const datasetCsv: Record<string, { csv: () => string; units: Record<string, string> }> = {
  [ITEM.dArcticSep]: { csv: seaIceCsv(SEA_ICE.arcticSep), units: SEA_ICE_UNITS },
  [ITEM.dAntarcticFeb]: { csv: seaIceCsv(SEA_ICE.antarcticFeb), units: SEA_ICE_UNITS },
  [ITEM.dArcticMar]: { csv: seaIceCsv(SEA_ICE.arcticMar), units: SEA_ICE_UNITS },
  [ITEM.dAntarcticSep]: { csv: seaIceCsv(SEA_ICE.antarcticSep), units: SEA_ICE_UNITS },
};

// ------------------------------------------------------------ calendar
/**
 * Occasions NCPOR-style outreach calendars commonly observe.
 * NOTE: dates should be double-checked each year before publishing.
 */
export const occasions: { month: number; day: number; occasion: string; occasion_hi: string; kind: CalendarEntry["kind"]; tags: string[] }[] = [
  { month: 2, day: 11, occasion: "International Day of Women and Girls in Science", occasion_hi: "विज्ञान में महिलाओं और बालिकाओं का अंतर्राष्ट्रीय दिवस", kind: "occasion", tags: ["students", "outreach"] },
  { month: 2, day: 28, occasion: "National Science Day", occasion_hi: "राष्ट्रीय विज्ञान दिवस", kind: "occasion", tags: ["students", "schools", "outreach"] },
  { month: 3, day: 8, occasion: "International Women's Day", occasion_hi: "अंतर्राष्ट्रीय महिला दिवस", kind: "occasion", tags: ["outreach"] },
  { month: 4, day: 22, occasion: "Earth Day", occasion_hi: "पृथ्वी दिवस", kind: "occasion", tags: ["glacier", "sea ice", "cryosphere"] },
  { month: 6, day: 5, occasion: "World Environment Day", occasion_hi: "विश्व पर्यावरण दिवस", kind: "occasion", tags: ["glacier", "cryosphere"] },
  { month: 6, day: 8, occasion: "World Oceans Day", occasion_hi: "विश्व महासागर दिवस", kind: "occasion", tags: ["Southern Ocean", "fjord", "marine life", "sea ice"] },
  { month: 9, day: 14, occasion: "Hindi Diwas", occasion_hi: "हिंदी दिवस", kind: "occasion", tags: ["हिंदी"] },
  { month: 11, day: 1, occasion: "Expedition milestone: 46th Indian Scientific Expedition to Antarctica", occasion_hi: "अभियान पड़ाव: अंटार्कटिका के लिए 46वाँ भारतीय वैज्ञानिक अभियान", kind: "milestone", tags: ["46-ISEA", "Antarctica"] },
  { month: 12, day: 1, occasion: "Antarctica Day", occasion_hi: "अंटार्कटिका दिवस", kind: "occasion", tags: ["Antarctica", "sea ice", "penguin"] },
];
