/**
 * Demo seed data — the single source of truth for both the in-memory demo
 * store and `supabase/seed.sql` (generated by `npm run seed:sql`).
 *
 * RULES (see BUILD_PROMPT §19):
 *  - Everything here is either a plain external link to a real public NCPOR
 *    page (credited, no copied content) or clearly labelled Sample
 *    (`is_sample: true`). Sample text is fictional and says so.
 *  - No invented facts about NCPOR or polar science.
 */
import type { CalendarEntry, Expedition, Item, Organization, Profile, Station } from "@/lib/types";

/** Deterministic, valid v4-shaped UUIDs for seed rows. */
export const sid = (n: number) => `00000000-0000-4000-a000-${String(n).padStart(12, "0")}`;

export const ORG_ID = sid(1);
export const org: Organization = { id: ORG_ID, name: "NCPOR", slug: "ncpor", logo_url: null };

/** Demo-mode personas (demo store only; not inserted into Supabase). */
export const demoProfiles: Profile[] = [
  { id: sid(11), full_name: "Sample Member", email: "member@demo.local", avatar_url: null, role: "member", org_id: ORG_ID },
  { id: sid(12), full_name: "Sample Curator", email: "curator@demo.local", avatar_url: null, role: "curator", org_id: ORG_ID },
  { id: sid(13), full_name: "Sample Reviewer", email: "reviewer@demo.local", avatar_url: null, role: "reviewer", org_id: ORG_ID },
  { id: sid(14), full_name: "Sample Admin", email: "admin@demo.local", avatar_url: null, role: "admin", org_id: ORG_ID },
];

/**
 * Stations. Coordinates are APPROXIMATE (rounded, from general public
 * references) and must be verified against NCPOR before any official use.
 */
export const stations: Station[] = [
  { id: sid(21), name: "Maitri", region: "antarctica", lat: -70.77, lng: 11.73, description: "Indian Antarctic research station in the Schirmacher Oasis region (coordinates approximate)." },
  { id: sid(22), name: "Bharati", region: "antarctica", lat: -69.41, lng: 76.19, description: "Indian Antarctic research station in the Larsemann Hills region (coordinates approximate)." },
  { id: sid(23), name: "Himadri", region: "arctic", lat: 78.92, lng: 11.93, description: "Indian Arctic research station at Ny-Ålesund, Svalbard (coordinates approximate)." },
  { id: sid(24), name: "Himansh", region: "himalaya", lat: 32.4, lng: 77.6, description: "Indian high-altitude research station in the Himalaya (coordinates approximate)." },
];

const EXP = { e45: sid(31), e46: sid(32), arc: sid(33), him: sid(34), soe: sid(35) };

export const expeditions: Expedition[] = [
  {
    id: EXP.e45, org_id: ORG_ID, code: "45-ISEA", region: "antarctica",
    title: "45th Indian Scientific Expedition to Antarctica",
    summary: "Sample overview. The summer component of this expedition has concluded. The linked items below are fictional samples created to demonstrate the portal; they are not the expedition's real reports or data.",
    start_date: "2025-11-01", end_date: "2026-03-31", status: "completed", cover_url: "art:antarctic-coast", station_id: sid(21), is_sample: true,
  },
  {
    id: EXP.e46, org_id: ORG_ID, code: "46-ISEA", region: "antarctica",
    title: "46th Indian Scientific Expedition to Antarctica",
    summary: "Planned for October/November 2026. This page will collect reports, data, photos and activities as they are released. Dates shown are indicative.",
    start_date: "2026-10-15", end_date: null, status: "planned", cover_url: "art:ship-ice", station_id: sid(22), is_sample: true,
  },
  {
    id: EXP.arc, org_id: ORG_ID, code: "ARC-2025-S", region: "arctic",
    title: "Arctic Summer Campaign (Sample)",
    summary: "A fictional sample Arctic campaign based at Himadri, used to demonstrate how fjord, weather and outreach material link together.",
    start_date: "2025-06-10", end_date: "2025-07-15", status: "completed", cover_url: "art:fjord", station_id: sid(23), is_sample: true,
  },
  {
    id: EXP.him, org_id: ORG_ID, code: "HIM-2025-S", region: "himalaya",
    title: "Himalayan Glacier Field Season (Sample)",
    summary: "A fictional sample glacier field season near Himansh, used to demonstrate glacier field notes, photos and school outreach.",
    start_date: "2025-09-01", end_date: "2025-10-05", status: "completed", cover_url: "art:glacier", station_id: sid(24), is_sample: true,
  },
  {
    id: EXP.soe, org_id: ORG_ID, code: "SOE-2024-S", region: "southern_ocean",
    title: "Southern Ocean Transect Cruise (Sample)",
    summary: "A fictional sample ocean cruise used to demonstrate ship-based reports and datasets.",
    start_date: "2024-12-20", end_date: "2025-02-10", status: "completed", cover_url: "art:ocean", station_id: null, is_sample: true,
  },
];

const T0 = "2026-01-05T09:00:00.000Z";

type SeedItem = Omit<Item, "org_id" | "created_at" | "updated_at" | "created_by" | "status" | "visibility" | "embargo_until"> &
  Partial<Pick<Item, "status" | "visibility" | "embargo_until" | "created_at">>;

const base = (i: SeedItem): Item => ({
  status: "published",
  visibility: "public",
  embargo_until: null,
  created_at: T0,
  ...i,
  org_id: ORG_ID,
  created_by: null,
  updated_at: i.created_at ?? T0,
});

export const ITEM = {
  r45: sid(101), rHim: sid(102), rArc: sid(103), rSoe: sid(104), rInternal: sid(105), rEmbargo: sid(106),
  dAws: sid(111), dIce: sid(112), dNpdc: sid(113), dMet: sid(114),
  pSnow: sid(121), pDebris: sid(122), pFjordHi: sid(123), pComic: sid(124),
  ph1: sid(131), ph2: sid(132), ph3: sid(133), ph4: sid(134), ph5: sid(135), ph6: sid(136),
  v1: sid(141), v2: sid(142), v3: sid(143),
  a1: sid(151), a2: sid(152), a3: sid(153), aAnt: sid(154), a46: sid(155),
};

const SAMPLE_LICENSE = "CC BY 4.0 (sample content)";

export const items: Item[] = [
  // ------------------------------------------------------------ reports
  base({ id: ITEM.r45, type: "report", title: "45-ISEA Summer Field Log (Sample)", description: "A fictional sample field log showing how an expedition report appears in DhruvGyani: logistics, weather-station servicing and sea-ice observations.", expedition_id: EXP.e45, station_id: sid(21), discipline: ["Meteorology", "Glaciology"], tags: ["sea ice", "weather station", "snow pit"], authors: ["Sample Field Team"], event_date: "2026-01-21", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "/samples/45-isea-field-log-sample.pdf" }),
  base({ id: ITEM.rHim, type: "report", title: "Glacier Mass-Balance Field Notes (Sample)", description: "Fictional sample field notes from a Himalayan glacier season: stake network, snow density and debris cover observations.", expedition_id: EXP.him, station_id: sid(24), discipline: ["Glaciology"], tags: ["glacier", "mass balance", "ablation"], authors: ["Sample Glacier Team"], event_date: "2025-09-28", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "/samples/himalaya-glacier-notes-sample.pdf" }),
  base({ id: ITEM.rArc, type: "report", title: "Himadri Summer Campaign Overview (Sample)", description: "Fictional sample overview of an Arctic summer campaign: fjord transects, weather records and outreach.", expedition_id: EXP.arc, station_id: sid(23), discipline: ["Oceanography", "Meteorology"], tags: ["fjord", "Arctic", "CTD"], authors: ["Sample Arctic Team"], event_date: "2025-07-12", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "/samples/arctic-campaign-sample.pdf" }),
  base({ id: ITEM.rSoe, type: "report", title: "Southern Ocean Transect Cruise Summary (Sample)", description: "Fictional sample cruise summary: CTD casts, plankton net sampling and sea-state notes.", expedition_id: EXP.soe, station_id: null, discipline: ["Oceanography", "Biology"], tags: ["Southern Ocean", "krill", "CTD"], authors: ["Sample Cruise Team"], event_date: "2025-01-30", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "/samples/southern-ocean-cruise-sample.pdf" }),
  base({ id: ITEM.rInternal, type: "report", title: "Station Logistics Debrief (Sample, internal)", description: "Fictional internal debrief. Marked internal: never shown publicly and never sent to an AI service.", expedition_id: EXP.e45, station_id: sid(21), discipline: ["Logistics"], tags: ["logistics"], authors: ["Sample Station Team"], event_date: "2026-02-20", language: "en", license: null, source_url: null, external_url: null, is_sample: true, status: "draft", visibility: "internal" }),
  base({ id: ITEM.rEmbargo, type: "report", title: "Preliminary Snow Chemistry Results (Sample, embargoed)", description: "Fictional embargoed item. Hidden from public pages, search and AI until the release date.", expedition_id: EXP.e45, station_id: sid(21), discipline: ["Chemistry"], tags: ["snow chemistry"], authors: ["Sample Lab Team"], event_date: "2026-03-10", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, status: "published", visibility: "public", embargo_until: "2026-12-01T00:00:00.000Z" }),

  // ------------------------------------------------------------ datasets
  base({ id: ITEM.dAws, type: "dataset", title: "Sample AWS Air Temperature, Jan–Feb 2026 (synthetic)", description: "Synthetic daily air-temperature series generated for demonstration. Not real observations.", expedition_id: EXP.e45, station_id: sid(21), discipline: ["Meteorology"], tags: ["temperature", "weather station", "time series"], authors: ["DhruvGyani demo generator"], event_date: "2026-02-28", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "/samples/aws-temperature-sample.csv" }),
  base({ id: ITEM.dIce, type: "dataset", title: "Sample Sea-Ice Index, 2020–2025 (synthetic)", description: "Synthetic monthly index values generated for demonstration. Not real observations.", expedition_id: EXP.soe, station_id: null, discipline: ["Oceanography"], tags: ["sea ice", "index", "monthly"], authors: ["DhruvGyani demo generator"], event_date: "2025-12-31", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "/samples/sea-ice-index-sample.csv" }),
  base({ id: ITEM.dNpdc, type: "dataset", title: "National Polar Data Center (NPDC) — external link", description: "External link to NCPOR's National Polar Data Center. Data is hosted and licensed by NCPOR; DhruvGyani links and credits only.", expedition_id: null, station_id: null, discipline: ["Data"], tags: ["data portal", "NCPOR"], authors: ["NCPOR"], event_date: null, language: "en", license: "See source site", source_url: "https://npdc.ncpor.res.in", external_url: "https://npdc.ncpor.res.in", is_sample: false }),
  base({ id: ITEM.dMet, type: "dataset", title: "Antarctic Meteorological Data Portal — external link", description: "External link to NCPOR's Antarctic meteorological data portal. Data is hosted and licensed by NCPOR; DhruvGyani links and credits only.", expedition_id: null, station_id: null, discipline: ["Meteorology", "Data"], tags: ["weather", "data portal", "NCPOR"], authors: ["NCPOR"], event_date: null, language: "en", license: "See source site", source_url: "https://data.ncpor.res.in", external_url: "https://data.ncpor.res.in", is_sample: false }),

  // ------------------------------------------------------------ publications
  base({ id: ITEM.pSnow, type: "publication", title: "Snow-Pit Stratigraphy at a Coastal Antarctic Site (Sample abstract)", description: "A fictional sample abstract showing how publications are archived with authors, citation export and explainers.", expedition_id: EXP.e45, station_id: sid(21), discipline: ["Glaciology"], tags: ["snow pit", "stratigraphy"], authors: ["A. Sample", "B. Example"], event_date: "2026-04-15", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true }),
  base({ id: ITEM.pDebris, type: "publication", title: "Debris Cover and Surface Melt on a Himalayan Glacier (Sample abstract)", description: "A fictional sample abstract about debris-covered ice, used to demonstrate the Library and Studio.", expedition_id: EXP.him, station_id: sid(24), discipline: ["Glaciology"], tags: ["debris cover", "melt", "glacier"], authors: ["C. Demo", "D. Placeholder"], event_date: "2025-12-01", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true }),
  base({ id: ITEM.pFjordHi, type: "publication", title: "आर्कटिक फ्योर्ड में जल तापमान अवलोकन (नमूना सार)", description: "हिंदी में एक काल्पनिक नमूना सार, जो दिखाता है कि हिंदी सामग्री कैसे संग्रहित और खोजी जाती है। यह वास्तविक डेटा नहीं है।", expedition_id: EXP.arc, station_id: sid(23), discipline: ["Oceanography"], tags: ["फ्योर्ड", "आर्कटिक", "समुद्री तापमान"], authors: ["नमूना लेखक"], event_date: "2025-08-20", language: "hi", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true }),
  base({ id: ITEM.pComic, type: "publication", title: "“Polar Sciences: A Peek into NCPOR” comic book — external link", description: "External link to NCPOR's news post about its comic book. The comic is NCPOR's work; DhruvGyani links and credits only.", expedition_id: null, station_id: null, discipline: ["Outreach"], tags: ["comic", "students", "NCPOR"], authors: ["NCPOR"], event_date: null, language: "en", license: "See source site", source_url: "https://www.ncpor.res.in/news/view/790", external_url: "https://www.ncpor.res.in/news/view/790", is_sample: false }),

  // ------------------------------------------------------------ photos (illustrations, not real photographs)
  base({ id: ITEM.ph1, type: "photo", title: "Aurora over a coastal station (Sample illustration)", description: "Illustration used as a stand-in for an expedition photograph.", expedition_id: EXP.e45, station_id: sid(21), discipline: ["Outreach"], tags: ["aurora", "night sky"], authors: ["DhruvGyani design"], event_date: "2026-01-15", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:aurora", alt_text: "Illustration: green and teal aurora bands above a snowy coastline with a small station building." }),
  base({ id: ITEM.ph2, type: "photo", title: "Snow-pit sampling (Sample illustration)", description: "Illustration of snow-pit sampling used as a stand-in photograph.", expedition_id: EXP.e45, station_id: sid(21), discipline: ["Glaciology"], tags: ["snow pit", "fieldwork"], authors: ["DhruvGyani design"], event_date: "2026-01-18", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:snowfield", alt_text: "Illustration: a flat white snowfield under a pale blue sky with distant ice hills." }),
  base({ id: ITEM.ph3, type: "photo", title: "Ship in pack ice (Sample illustration)", description: "Illustration of a research vessel in pack ice.", expedition_id: EXP.soe, station_id: null, discipline: ["Oceanography"], tags: ["ship", "pack ice"], authors: ["DhruvGyani design"], event_date: "2025-01-12", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:ship-ice", alt_text: "Illustration: a ship silhouette among floating ice floes at dusk." }),
  base({ id: ITEM.ph4, type: "photo", title: "Glacier snout in the Himalaya (Sample illustration)", description: "Illustration of a glacier snout below high peaks.", expedition_id: EXP.him, station_id: sid(24), discipline: ["Glaciology"], tags: ["glacier", "mountains"], authors: ["DhruvGyani design"], event_date: "2025-09-20", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:glacier", alt_text: "Illustration: jagged snow-capped peaks above a grey-blue glacier tongue." }),
  base({ id: ITEM.ph5, type: "photo", title: "Arctic fjord at midnight sun (Sample illustration)", description: "Illustration of a calm Arctic fjord.", expedition_id: EXP.arc, station_id: sid(23), discipline: ["Oceanography"], tags: ["fjord", "Arctic"], authors: ["DhruvGyani design"], event_date: "2025-06-30", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:fjord", alt_text: "Illustration: dark mountains reflected in a calm fjord under a warm low sun." }),
  base({ id: ITEM.ph6, type: "photo", title: "Weather station mast (Sample illustration)", description: "Illustration of an automatic weather station.", expedition_id: EXP.e45, station_id: sid(22), discipline: ["Meteorology"], tags: ["weather station"], authors: ["DhruvGyani design"], event_date: "2026-01-10", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:antarctic-coast", alt_text: "Illustration: icy coastline with low hills under a clear sky." }),

  // ------------------------------------------------------------ videos (placeholders with transcripts)
  base({ id: ITEM.v1, type: "video", title: "A day at a research station (Sample video placeholder)", description: "Placeholder for an outreach video, with a sample transcript. No real footage is included.", expedition_id: EXP.e45, station_id: sid(21), discipline: ["Outreach"], tags: ["station life", "students"], authors: ["DhruvGyani demo"], event_date: "2026-02-02", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:aurora" }),
  base({ id: ITEM.v2, type: "video", title: "How an ice core is drilled (Sample video placeholder)", description: "Placeholder explainer video with a sample transcript.", expedition_id: null, station_id: null, discipline: ["Glaciology", "Outreach"], tags: ["ice core", "explainer"], authors: ["DhruvGyani demo"], event_date: "2025-11-20", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:snowfield" }),
  base({ id: ITEM.v3, type: "video", title: "Launching a weather balloon (Sample video placeholder)", description: "Placeholder video with a sample transcript.", expedition_id: EXP.arc, station_id: sid(23), discipline: ["Meteorology"], tags: ["weather balloon"], authors: ["DhruvGyani demo"], event_date: "2025-07-02", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true, media_url: "art:fjord" }),

  // ------------------------------------------------------------ activities
  base({ id: ITEM.a1, type: "activity", title: "Polar Science Week: school outreach (Sample)", description: "Fictional sample outreach activity record: talks and hands-on demonstrations for school students.", expedition_id: null, station_id: null, discipline: ["Outreach"], tags: ["schools", "students"], authors: ["Sample Outreach Cell"], event_date: "2026-02-28", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true }),
  base({ id: ITEM.a2, type: "activity", title: "Teacher workshop on the cryosphere (Sample)", description: "Fictional sample teacher workshop with a downloadable teacher pack.", expedition_id: null, station_id: null, discipline: ["Outreach", "Education"], tags: ["teachers", "cryosphere"], authors: ["Sample Outreach Cell"], event_date: "2025-12-01", language: "en", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true }),
  base({ id: ITEM.a3, type: "activity", title: "हिंदी पखवाड़ा: ध्रुवीय विज्ञान प्रश्नोत्तरी (नमूना)", description: "हिंदी में एक काल्पनिक नमूना गतिविधि: छात्रों के लिए ध्रुवीय विज्ञान प्रश्नोत्तरी।", expedition_id: null, station_id: null, discipline: ["Outreach"], tags: ["हिंदी", "प्रश्नोत्तरी"], authors: ["नमूना आउटरीच सेल"], event_date: "2025-09-14", language: "hi", license: SAMPLE_LICENSE, source_url: null, external_url: null, is_sample: true }),
  base({ id: ITEM.aAnt, type: "activity", title: "NCPOR Antarctic programme — external link", description: "External link to NCPOR's page about its Antarctic programme. Content is hosted by NCPOR; DhruvGyani links and credits only.", expedition_id: null, station_id: null, discipline: ["Programme"], tags: ["Antarctica", "NCPOR"], authors: ["NCPOR"], event_date: null, language: "en", license: "See source site", source_url: "https://ncpor.res.in/antarcticas", external_url: "https://ncpor.res.in/antarcticas", is_sample: false }),
  base({ id: ITEM.a46, type: "activity", title: "46-ISEA webpage advertisement (PDF) — external link", description: "External link to NCPOR's advertisement document for the 46th Indian Scientific Expedition to Antarctica. Hosted by NCPOR; linked and credited only.", expedition_id: EXP.e46, station_id: null, discipline: ["Programme"], tags: ["46-ISEA", "announcement"], authors: ["NCPOR"], event_date: null, language: "en", license: "See source site", source_url: "http://isea.ncpor.res.in/forms/46-ISEA%20Webpage%20Advertisment.pdf", external_url: "http://isea.ncpor.res.in/forms/46-ISEA%20Webpage%20Advertisment.pdf", is_sample: false }),
];

/**
 * Sample document text, page by page. Every page is fictional and labelled.
 * Also used by `scripts/make-sample-pdfs.ts` to render the sample PDFs.
 */
export const sampleDocs: Record<string, string[]> = {
  [ITEM.r45]: [
    "SAMPLE - not real data. 45-ISEA Summer Field Log. This fictional log demonstrates how an expedition report is archived. The summer field team worked from Maitri between 8 January 2026 and 21 January 2026. Daily planning meetings were held at 0800 hours and all field parties carried satellite messengers.",
    "SAMPLE - not real data. Weather-station servicing. The team serviced 6 automatic weather stations along the coastal traverse. Batteries were replaced at 4 stations and one wind sensor was recalibrated. Recorded air temperature during the servicing period ranged from -12.4 °C to 2.1 °C.",
    "SAMPLE - not real data. Snow and sea-ice observations. The team dug 12 snow pits and recorded density every 10 cm. Fast ice near the landing site was observed to break up in the final week of the campaign. Photographs and field sheets were uploaded to the internal archive for review.",
  ],
  [ITEM.rHim]: [
    "SAMPLE - not real data. Glacier Mass-Balance Field Notes. This fictional note describes a glacier field season near Himansh from 1 September 2025 to 5 October 2025. The team re-measured a network of 34 ablation stakes on the glacier tongue.",
    "SAMPLE - not real data. Snow density was measured at 3 accumulation-zone pits above 4,850 m. Debris cover on the lower tongue made several stakes hard to reach. The field team recommends replacing 5 stakes next season.",
  ],
  [ITEM.rArc]: [
    "SAMPLE - not real data. Himadri Summer Campaign Overview. This fictional overview covers an 18-day campaign at Ny-Ålesund in June and July 2025. The team completed 3 fjord transects by small boat and logged weather observations twice daily.",
    "SAMPLE - not real data. Outreach during the campaign included 2 live video calls with schools in India. Water samples were stored at 4 °C before shipment. All data sheets were digitised at the end of each week.",
  ],
  [ITEM.rSoe]: [
    "SAMPLE - not real data. Southern Ocean Transect Cruise Summary. This fictional summary describes a ship-based transect from 20 December 2024 to 10 February 2025. The science team completed 42 CTD casts measuring temperature, salinity and depth.",
    "SAMPLE - not real data. Plankton nets were deployed at 15 stations and krill were observed in several net hauls. Rough sea states on 6 days delayed deck operations. Samples were preserved for later laboratory analysis.",
  ],
  [ITEM.rInternal]: ["SAMPLE - internal. Station logistics debrief: fuel handling, generator maintenance schedule and cargo notes. This item is internal and must never be sent to an AI service."],
  [ITEM.rEmbargo]: ["SAMPLE - embargoed. Preliminary snow chemistry results pending peer review. This item is embargoed and must not appear publicly or be sent to an AI service before its release date."],
  [ITEM.pSnow]: [
    "SAMPLE abstract - not a real publication. We describe snow-pit stratigraphy from 12 pits dug at a coastal Antarctic site during a summer field season. Density was recorded every 10 cm. Layers of wind-packed snow alternated with softer layers. The sample shows how abstracts are stored, cited and explained at three levels.",
  ],
  [ITEM.pDebris]: [
    "SAMPLE abstract - not a real publication. Debris-covered glaciers are common in the Himalaya. In this fictional study, stake readings from 34 stakes were compared between clean ice and debris-covered ice. The sample is used to demonstrate the Content Studio and Trust Panel.",
  ],
  [ITEM.pFjordHi]: [
    "नमूना सार - वास्तविक प्रकाशन नहीं। इस काल्पनिक अध्ययन में आर्कटिक फ्योर्ड में 3 अनुप्रस्थ मार्गों पर जल तापमान दर्ज किया गया। नमूने 4 °C पर रखे गए। यह सार दिखाता है कि हिंदी सामग्री कैसे खोजी और समझाई जाती है।",
  ],
  [ITEM.v1]: ["SAMPLE transcript. Good morning from the station. Our day starts with a weather briefing, then field teams check their radios and set out. In the evening everyone shares what they observed. This is a placeholder transcript for a demo video."],
  [ITEM.v2]: ["SAMPLE transcript. An ice core is drilled using a hollow drill that cuts a cylinder of ice. Each section is lifted, logged and packed in insulated boxes. This is a placeholder transcript for a demo video."],
  [ITEM.v3]: ["SAMPLE transcript. A weather balloon carries a small instrument package called a radiosonde. It sends back temperature, humidity and wind readings as it rises. This is a placeholder transcript for a demo video."],
  [ITEM.a1]: ["SAMPLE activity record. Polar Science Week included talks for school students, a hands-on ice demonstration and a short quiz. 120 students took part in this fictional sample event."],
  [ITEM.a2]: ["SAMPLE activity record. A one-day teacher workshop introduced the cryosphere, polar stations and classroom activities. 30 teachers received a sample teacher pack."],
  [ITEM.a3]: ["नमूना गतिविधि रिकॉर्ड। हिंदी पखवाड़े के दौरान छात्रों के लिए ध्रुवीय विज्ञान प्रश्नोत्तरी आयोजित की गई। इस काल्पनिक कार्यक्रम में 80 छात्रों ने भाग लिया।"],
  [ITEM.ph1]: ["Illustration caption: aurora bands above a coastal station. Sample illustration, not a photograph."],
  [ITEM.ph2]: ["Illustration caption: a snowfield where snow pits are dug for sampling. Sample illustration, not a photograph."],
  [ITEM.ph3]: ["Illustration caption: a research ship moving through pack ice. Sample illustration, not a photograph."],
  [ITEM.ph4]: ["Illustration caption: a Himalayan glacier snout below high peaks. Sample illustration, not a photograph."],
  [ITEM.ph5]: ["Illustration caption: a calm Arctic fjord under the midnight sun. Sample illustration, not a photograph."],
  [ITEM.ph6]: ["Illustration caption: an icy coastline where automatic weather stations are serviced. Sample illustration, not a photograph."],
  [ITEM.dNpdc]: ["External link: National Polar Data Center, hosted by NCPOR. Visit the source site for datasets, metadata and licensing."],
  [ITEM.dMet]: ["External link: Antarctic meteorological data portal, hosted by NCPOR. Visit the source site for data and terms of use."],
  [ITEM.pComic]: ["External link: NCPOR news post about the comic book Polar Sciences: A Peek into NCPOR. Visit the source site to read it."],
  [ITEM.aAnt]: ["External link: NCPOR page about the Indian Antarctic programme. Visit the source site for details."],
  [ITEM.a46]: ["External link: NCPOR advertisement document for the 46th Indian Scientific Expedition to Antarctica. Visit the source site for details."],
};

/** Deterministic chunk IDs: item order × page. */
export function chunkId(itemId: string, page: number) {
  const n = Number(itemId.slice(-4));
  return sid(10000 + n * 10 + page);
}

// ------------------------------------------------------------ synthetic CSVs
function lcg(seed: number) {
  let s = seed;
  return () => {
    s = (s * 1664525 + 1013904223) % 4294967296;
    return s / 4294967296;
  };
}

/** Synthetic daily air temperature (°C) — clearly fake, deterministic. */
export function awsCsv(): string {
  const rnd = lcg(46);
  const rows = ["date,air_temp_c,wind_speed_ms,relative_humidity_pct"];
  const start = Date.UTC(2026, 0, 1);
  for (let d = 0; d < 59; d++) {
    const date = new Date(start + d * 86400000).toISOString().slice(0, 10);
    const t = (-3 + 4 * Math.sin((d / 59) * Math.PI) - d * 0.06 + (rnd() - 0.5) * 3).toFixed(1);
    const w = (4 + rnd() * 9).toFixed(1);
    const rh = d % 17 === 5 ? "" : String(Math.round(55 + rnd() * 30));
    rows.push(`${date},${t},${w},${rh}`);
  }
  return rows.join("\n") + "\n";
}

/** Synthetic monthly sea-ice index (unitless) — clearly fake, deterministic. */
export function seaIceCsv(): string {
  const rnd = lcg(2020);
  const rows = ["month,sea_ice_index,anomaly_index"];
  for (let y = 2020; y <= 2025; y++) {
    for (let m = 1; m <= 12; m++) {
      const season = Math.cos(((m - 9) / 12) * 2 * Math.PI);
      const v = 50 + 35 * season + (rnd() - 0.5) * 6;
      rows.push(`${y}-${String(m).padStart(2, "0")},${v.toFixed(2)},${((rnd() - 0.5) * 4).toFixed(2)}`);
    }
  }
  return rows.join("\n") + "\n";
}

export const datasetCsv: Record<string, { csv: () => string; units: Record<string, string> }> = {
  [ITEM.dAws]: { csv: awsCsv, units: { air_temp_c: "°C", wind_speed_ms: "m/s", relative_humidity_pct: "%" } },
  [ITEM.dIce]: { csv: seaIceCsv, units: { sea_ice_index: "index (unitless)", anomaly_index: "index (unitless)" } },
};

// ------------------------------------------------------------ calendar
/**
 * Occasions NCPOR-style outreach calendars commonly observe.
 * NOTE: dates should be double-checked each year before publishing.
 */
export const occasions: { month: number; day: number; occasion: string; occasion_hi: string; kind: CalendarEntry["kind"]; tags: string[] }[] = [
  { month: 2, day: 11, occasion: "International Day of Women and Girls in Science", occasion_hi: "विज्ञान में महिलाओं और बालिकाओं का अंतर्राष्ट्रीय दिवस", kind: "occasion", tags: ["students", "outreach"] },
  { month: 2, day: 28, occasion: "National Science Day", occasion_hi: "राष्ट्रीय विज्ञान दिवस", kind: "occasion", tags: ["students", "schools", "outreach"] },
  { month: 3, day: 8, occasion: "International Women's Day", occasion_hi: "अंतर्राष्ट्रीय महिला दिवस", kind: "occasion", tags: ["outreach"] },
  { month: 4, day: 22, occasion: "Earth Day", occasion_hi: "पृथ्वी दिवस", kind: "occasion", tags: ["glacier", "sea ice", "cryosphere"] },
  { month: 6, day: 5, occasion: "World Environment Day", occasion_hi: "विश्व पर्यावरण दिवस", kind: "occasion", tags: ["glacier", "cryosphere"] },
  { month: 6, day: 8, occasion: "World Oceans Day", occasion_hi: "विश्व महासागर दिवस", kind: "occasion", tags: ["Southern Ocean", "fjord", "krill", "sea ice"] },
  { month: 9, day: 14, occasion: "Hindi Diwas", occasion_hi: "हिंदी दिवस", kind: "occasion", tags: ["हिंदी"] },
  { month: 11, day: 1, occasion: "Expedition milestone: 46th Indian Scientific Expedition to Antarctica (planned Oct/Nov 2026)", occasion_hi: "अभियान पड़ाव: अंटार्कटिका के लिए 46वाँ भारतीय वैज्ञानिक अभियान (अक्टूबर/नवंबर 2026 में प्रस्तावित)", kind: "milestone", tags: ["46-ISEA", "Antarctica"] },
  { month: 12, day: 1, occasion: "Antarctica Day", occasion_hi: "अंटार्कटिका दिवस", kind: "occasion", tags: ["Antarctica", "sea ice", "weather station"] },
];
