/** Concatenate migrations + seed into supabase/all.sql (paste into the Supabase SQL editor). */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(process.cwd(), "supabase");
const migrations = readdirSync(join(root, "migrations")).filter((f) => f.endsWith(".sql")).sort();
const parts = [
  "-- DhruvGyani: all migrations + seed, in order. GENERATED by `npm run sql:bundle`.",
  "-- Paste into Supabase → SQL Editor → Run, on a fresh project.",
  "",
];
for (const f of migrations) parts.push(`-- ============================================================ ${f}`, readFileSync(join(root, "migrations", f), "utf8"));
parts.push("-- ============================================================ seed.sql", readFileSync(join(root, "seed.sql"), "utf8"));
writeFileSync(join(root, "all.sql"), parts.join("\n"));
console.log(`✔ wrote supabase/all.sql (${migrations.length} migrations + seed)`);
