/**
 * Generate supabase/seed.sql from the TypeScript seed module (single source
 * of truth shared with the in-memory demo store). Idempotent: every insert
 * uses ON CONFLICT DO NOTHING.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { buildCalendar } from "../src/lib/calendar";
import { profileCsv } from "../src/lib/datasets/profile";
import { isPubliclyVisible } from "../src/lib/policy";
import { chunkId, datasetCsv, expeditions, items, org, sampleDocs, stations } from "../src/lib/seed/data";
import { glossarySeed } from "../src/lib/seed/glossary";
import { seedExplainers, seedGenerations } from "../src/lib/seed/packs";
import { verifyClaimsOffline } from "../src/lib/trust/claims";
import type { Chunk } from "../src/lib/types";

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "boolean") return v ? "true" : "false";
  if (typeof v === "number") return String(v);
  return `'${String(v).replace(/'/g, "''")}'`;
};
const arr = (a: string[], type = "text") => (a.length ? `array[${a.map(q).join(",")}]::${type}[]` : `'{}'::${type}[]`);
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const out: string[] = [
  "-- GENERATED by `npm run seed:sql` from src/lib/seed/*.ts — do not edit by hand.",
  "-- All sample content is fictional and labelled (is_sample = true).",
  "begin;",
];

out.push(`insert into public.organizations (id, name, slug, logo_url) values (${q(org.id)}, ${q(org.name)}, ${q(org.slug)}, null) on conflict do nothing;`);

for (const s of stations) {
  out.push(
    `insert into public.stations (id, name, region, lat, lng, description) values (${q(s.id)}, ${q(s.name)}, ${q(s.region)}, ${s.lat}, ${s.lng}, ${q(s.description)}) on conflict do nothing;`,
  );
}

for (const e of expeditions) {
  out.push(
    `insert into public.expeditions (id, org_id, code, region, title, summary, start_date, end_date, status, cover_url, station_id, is_sample) values (${[
      e.id, e.org_id, e.code, e.region, e.title, e.summary, e.start_date, e.end_date, e.status, e.cover_url, e.station_id,
    ].map(q).join(", ")}, ${q(e.is_sample)}) on conflict do nothing;`,
  );
}

for (const i of items) {
  out.push(
    `insert into public.items (id, org_id, type, title, description, expedition_id, station_id, discipline, tags, authors, event_date, language, license, source_url, external_url, media_url, alt_text, status, visibility, embargo_until, is_sample, created_at) values (${[
      i.id, i.org_id, i.type, i.title, i.description, i.expedition_id, i.station_id,
    ].map(q).join(", ")}, ${arr(i.discipline)}, ${arr(i.tags)}, ${arr(i.authors)}, ${[
      i.event_date, i.language, i.license, i.source_url, i.external_url, i.media_url ?? null, i.alt_text ?? null, i.status, i.visibility, i.embargo_until,
    ].map(q).join(", ")}, ${q(i.is_sample)}, ${q(i.created_at)}) on conflict do nothing;`,
  );
}

const chunks: Chunk[] = [];
for (const [itemId, pages] of Object.entries(sampleDocs)) {
  pages.forEach((content, p) => {
    const c = { id: chunkId(itemId, p + 1), item_id: itemId, page_no: p + 1, chunk_index: p, content };
    chunks.push(c);
    out.push(
      `insert into public.chunks (id, item_id, page_no, chunk_index, content) values (${q(c.id)}, ${q(c.item_id)}, ${c.page_no}, ${c.chunk_index}, ${q(c.content)}) on conflict do nothing;`,
    );
  });
}

for (const [itemId, d] of Object.entries(datasetCsv)) {
  const { rows: _rows, ...p } = profileCsv(d.csv(), d.units);
  void _rows;
  out.push(
    `insert into public.dataset_profiles (item_id, columns, row_count, time_range, units, stats, summary, sample_rows) values (${q(itemId)}, ${json(p.columns)}, ${p.row_count}, ${json(p.time_range)}, ${json(p.units)}, ${json(p.stats)}, null, ${json(p.sample_rows)}) on conflict (item_id) do nothing;`,
  );
}

for (const g of glossarySeed) {
  out.push(
    `insert into public.glossary (id, term, term_hi, meaning_en, meaning_hi) values (${[g.id, g.term, g.term_hi, g.meaning_en, g.meaning_hi].map(q).join(", ")}) on conflict do nothing;`,
  );
}

for (const c of buildCalendar(items.filter((i) => isPubliclyVisible(i)))) {
  out.push(
    `insert into public.content_calendar (id, date, occasion, occasion_hi, kind, suggested_item_ids, status) values (${[c.id, c.date, c.occasion, c.occasion_hi, c.kind].map(q).join(", ")}, ${arr(c.suggested_item_ids, "uuid")}, ${q(c.status)}) on conflict do nothing;`,
  );
}

for (const g of seedGenerations) {
  out.push(
    `insert into public.generations (id, org_id, item_ids, audience, language, channel, prompt_version, model, output, citations, slug, status, reviewed_at, published_at, created_at) values (${q(g.id)}, ${q(g.org_id)}, ${arr(g.item_ids, "uuid")}, ${[g.audience, g.language, g.channel, g.prompt_version, g.model].map(q).join(", ")}, ${json(g.output)}, ${json(g.citations)}, ${[g.slug, g.status, g.reviewed_at, g.published_at, g.created_at].map(q).join(", ")}) on conflict do nothing;`,
  );
  for (const c of verifyClaimsOffline(g.id, g.output, g.citations, chunks)) {
    out.push(
      `insert into public.generation_claims (generation_id, claim_text, chunk_id, verdict, note, number_misses) values (${[c.generation_id, c.claim_text, c.chunk_id, c.verdict, c.note].map(q).join(", ")}, ${arr(c.number_misses)});`,
    );
  }
}

for (const e of seedExplainers) {
  out.push(
    `insert into public.explainers (item_id, level, language, text, citations) values (${[e.item_id, e.level, e.language, e.text].map(q).join(", ")}, ${json(e.citations)}) on conflict (item_id, level, language) do nothing;`,
  );
}

out.push("commit;", "");
const path = join(process.cwd(), "supabase", "seed.sql");
writeFileSync(path, out.join("\n"));
console.log(`✔ wrote ${path} (${out.length} statements)`);
