/**
 * Generate small FICTIONAL sample PDFs and synthetic CSVs into public/samples/.
 * Every PDF page is stamped "SAMPLE - not real data". Text comes from
 * src/lib/seed/data.ts so the PDFs, chunks and citations always agree.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { PDFDocument, StandardFonts, degrees, rgb } from "pdf-lib";
import { datasetCsv, items, sampleDocs } from "../src/lib/seed/data";

const out = join(process.cwd(), "public", "samples");
mkdirSync(out, { recursive: true });

function wrap(text: string, font: { widthOfTextAtSize: (t: string, s: number) => number }, size: number, width: number) {
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let line = "";
  for (const w of words) {
    const next = line ? `${line} ${w}` : w;
    if (font.widthOfTextAtSize(next, size) > width) {
      lines.push(line);
      line = w;
    } else line = next;
  }
  if (line) lines.push(line);
  return lines;
}

for (const item of items) {
  if (!item.media_url?.endsWith(".pdf")) continue;
  const pages = sampleDocs[item.id] ?? [];
  const doc = await PDFDocument.create();
  doc.setTitle(`${item.title} — SAMPLE`);
  doc.setAuthor("DhruvGyani demo generator");
  doc.setSubject("Fictional sample document. Not real data.");
  doc.setLanguage("en-IN");
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  pages.forEach((text, i) => {
    const page = doc.addPage([595, 842]);
    const navy = rgb(0.03, 0.08, 0.15);
    page.drawRectangle({ x: 0, y: 792, width: 595, height: 50, color: rgb(0.23, 0.65, 0.88) });
    page.drawText("SAMPLE - not real data", { x: 40, y: 810, size: 14, font: bold, color: rgb(1, 1, 1) });
    page.drawText(`Page ${i + 1} of ${pages.length}`, { x: 480, y: 810, size: 10, font, color: rgb(1, 1, 1) });
    page.drawText("SAMPLE", { x: 120, y: 330, size: 120, font: bold, color: rgb(0.9, 0.93, 0.97), rotate: degrees(35) });
    if (i === 0) {
      wrap(item.title, bold, 20, 515).forEach((l, k) => page.drawText(l, { x: 40, y: 740 - k * 26, size: 20, font: bold, color: navy }));
    }
    const body = text.replace(/^SAMPLE - not real data\.\s*/, "");
    wrap(body, font, 12, 515).forEach((l, k) => page.drawText(l, { x: 40, y: (i === 0 ? 670 : 740) - k * 18, size: 12, font, color: navy }));
    page.drawText("Generated by DhruvGyani for demonstration. Fictional content. Not NCPOR data.", { x: 40, y: 30, size: 8, font, color: rgb(0.4, 0.45, 0.5) });
  });
  const name = item.media_url.split("/").pop()!;
  writeFileSync(join(out, name), await doc.save());
  console.log(`✔ public/samples/${name} (${pages.length} pages)`);
}

for (const item of items) {
  if (!item.media_url?.endsWith(".csv")) continue;
  const d = datasetCsv[item.id];
  if (!d) continue;
  const name = item.media_url.split("/").pop()!;
  writeFileSync(join(out, name), d.csv());
  console.log(`✔ public/samples/${name}`);
}
