import { z } from "zod";

/** Metadata suggestions shown to staff for confirmation. Never saved without a human. */
export const Suggestion = z.object({
  title: z.string().max(200).default(""),
  authors: z.array(z.string().max(120)).max(12).default([]),
  year: z.number().int().min(1950).max(2100).nullable().default(null),
  expedition_code: z.string().max(40).nullable().default(null),
  keywords: z.array(z.string().max(40)).max(10).default([]),
  language: z.enum(["en", "hi"]).default("en"),
  alt_text: z.string().max(400).nullable().default(null),
});
export type Suggestion = z.infer<typeof Suggestion>;

const STOP = new Set(
  "the and for with this that from were was are have has had been into over under their there which during also sample real data not page report team field these those than then such other more most some each only very will would could should about after before between within".split(" "),
);

function humanize(filename: string) {
  return filename
    .replace(/\.[a-z0-9]+$/i, "")
    .replace(/[_-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .replace(/^\w/, (c) => c.toUpperCase());
}

/** PDFs often repeat the title as the first body line: "A B C (x) A B C" → "A B C (x)". */
function dedupeRepeat(line: string): string {
  const w = line.split(/\s+/);
  for (let i = 3; i < w.length - 2; i++) {
    if (w[i] === w[0] && w[i + 1] === w[1] && w[i + 2] === w[2]) return w.slice(0, i).join(" ");
  }
  return line;
}

export function detectExpeditionCode(text: string, knownCodes: string[] = []): string | null {
  for (const code of knownCodes) if (new RegExp(`\\b${code.replace(/[-]/g, "[- ]?")}\\b`, "i").test(text)) return code;
  const m = text.match(/\b(\d{1,2})(?:st|nd|rd|th)?[- ]?ISEA\b/i) ?? text.match(/\b(\d{1,2})(?:st|nd|rd|th)\s+Indian\s+Scientific\s+Expedition\s+to\s+Antarctica/i);
  return m ? `${m[1]}-ISEA` : null;
}

/** Offline autofill: filename, first line, year, expedition code and top keywords. */
export function heuristicAutofill(input: { filename: string; text?: string; knownCodes?: string[] }): Suggestion {
  const text = (input.text ?? "").replace(/SAMPLE - not real data\.?/gi, " ");
  const firstLine =
    text
      .replace(/\bPage\s+\d+(\s+of\s+\d+)?\b/gi, "\n")
      .replace(/\bSAMPLE\b(?=\s+[A-Z0-9])/g, "\n")
      .replace(/Generated by[^.]*\./gi, "\n")
      .split(/\n|(?<=\.)\s/)
      .map((l) => dedupeRepeat(l.trim()))
      .find((l) => l.length > 8 && l.length < 140 && /\p{L}{3,}/u.test(l)) ?? "";
  const years = [...text.matchAll(/\b(19[5-9]\d|20[0-9]\d)\b/g)].map((m) => Number(m[1]));
  const yearCounts = new Map<number, number>();
  for (const y of years) yearCounts.set(y, (yearCounts.get(y) ?? 0) + 1);
  const year = [...yearCounts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0] ?? null;
  const words = new Map<string, number>();
  for (const w of text.toLowerCase().match(/\p{L}{4,}/gu) ?? []) if (!STOP.has(w)) words.set(w, (words.get(w) ?? 0) + 1);
  const keywords = [...words.entries()].sort((a, b) => b[1] - a[1]).slice(0, 6).map(([w]) => w);
  const authorsLine = text.match(/(?:authors?|by)\s*[:：]\s*([^\n.]{3,120})/i)?.[1];
  const hindi = (text.match(/[ऀ-ॿ]/g)?.length ?? 0) > text.length * 0.2;
  return Suggestion.parse({
    title: (firstLine || humanize(input.filename)).replace(/\.$/, "").slice(0, 200),
    authors: authorsLine ? authorsLine.split(/,|\band\b/).map((a) => a.trim()).filter(Boolean) : [],
    year,
    expedition_code: detectExpeditionCode(`${input.filename} ${text}`, input.knownCodes),
    keywords,
    language: hindi ? "hi" : "en",
    alt_text: null,
  });
}

export const AUTOFILL_PROMPT = (text: string, codes: string[]) => `You help archivists catalogue polar-science material.
From the document excerpt below, propose metadata. Use ONLY information present in the excerpt; use null or [] when unknown.
Known expedition codes: ${codes.join(", ")}.
Return JSON: {"title": string, "authors": string[], "year": number|null, "expedition_code": string|null, "keywords": string[] (max 8), "language": "en"|"hi"}

EXCERPT:
"""
${text.slice(0, 4000)}
"""`;

export const ALT_TEXT_PROMPT = `Write alt text for this photograph for a public science outreach website.
Describe only what is visible in one or two plain sentences (max 300 characters). Do not guess places, people's names or dates.
Return JSON: {"alt_text": string, "title": string}`;
